#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: double_pregnancy_convert
# Date: 2025.07.29
# Programmer: Barbara Nowak
# Purpose: Copy fp and sp data to different files
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [1]:
library(tidyverse)
library(dplyr)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

── Attaching core tidyverse packages ────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0
── Conflicts ──────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [4]:
double_pregnancy <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/data/double_pregnancy_240913.csv", header = TRUE)
#double_pregnancy |> summary()
#glimpse(double_pregnancy)
head(double_pregnancy)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5199 Sc10d0b0     NA         1        0         3
2 5200 S735d77f     NA         0        0         0
3 5201 S9cdfd5a     NA         0        0         0
4 5202 S9026714     NA         0        0         2
5 5204 S9deb4a6     NA         0        0         0
6 5205 S7b1a87b     NA         1        0         4
  Q1_Datum            Q1_Personnummer Avbruten_graviditet age_checked ⋯
1 2018-10-16 13:07:00 Pc10d0b0        0                   25          ⋯
2 2018-08-24 12:23:00 P735d77f        0                   25          ⋯
3 2018-08-14 07:21:00 P9cdfd5a        0                   25          ⋯
4 2019-01-02 18:05:00 P7ece52e        0                   25          ⋯
5 2019-11-20 20:13:00 P735d77f        0                   26          ⋯
6 2019-05-28 12:01:00 Pc10d0b0        0                   26          ⋯
  diffdays missfall.IUFD_week IUFD missfall missfall.IUFD_comments
1 NA       NA                  0    1       MISSFALL
2  0       NA                 NA   NA       NA
3  0       NA                 NA   NA       NA
4  0       NA                 NA   NA       NA
5  0       NA                 NA   NA       NA
6  0       NA                 NA   NA       NA
  Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
1 NA              NA                   NA          NA
2 39              Spontaneous          NA          NA
3 39              Spontaneous          NA          NA
4 41              Induction            NA          NA
5 39              Spontaneous          NA          NA
6 40              Spontaneous          NA          NA
  preeclampsia_epi_analysis
1 0
2 0
3 0
4 0
5 0
6 0

In [5]:
# 2 Convert char Q1_Datum to date format
double_pregnancy$Q1_Datum <- as.Date(double_pregnancy$Q1_Datum)

In [7]:
# 3 sort file; group duplicate Q1_Personnummer by date
sorted_double_pregnancy <- double_pregnancy |>
  arrange(Q1_Personnummer, Q1_Datum)
#glimpse(sorted_double_pregnancy)

In [8]:
# 3 Extract first and second pregnancy
kit_fp <- sorted_double_pregnancy |>
  group_by(Q1_Personnummer) |>
  slice(1)

In [9]:
kit_sp <- sorted_double_pregnancy |>
  group_by(Q1_Personnummer) |>
  slice(2)

In [10]:
# Check that num of rows and columns is still correct
dim(kit_fp)
dim(kit_sp)

[1]  59 566

[1]  59 566

In [11]:
# Check dates and pers# are correct
head(kit_fp)
head(kit_sp)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5265 Scf5931f     NA         0        0         0
2 5254 S14e664f     NA         0        0         1
3 5367 S194e21b     NA         0        0         0
4 5297 S1a267fa     NA         0        0         0
5 5300 S30bce16     NA         0        0         0
6 5208 Sa8397fa     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-12-13 P060d440        0                   30          ⋯ NA
2 2018-09-10 P14e664f        0                   30          ⋯  0
3 2018-11-16 P159f9c8        0                   36          ⋯  0
4 2019-05-23 P1a267fa        0                   32          ⋯  0
5 2018-04-18 P1d75300        0                   32          ⋯ NA
6 2018-03-14 P1ef420d        0                   27          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA    1       MISSED ABORTION        NA
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     38
5 NA                 NA   NA       NA                     NA
6 NA                 NA   NA       NA                     28
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 NA                   NA          NA    0
2 Induction            NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 NA                   NA          NA    0
6 Spontaneous          very_w28_31  1    0

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5253 S060d440     NA         0        0         1
2 5290 Sefe71fe     NA         0        0         1
3 5391 S159f9c8     NA         0        0         0
4 5332 Sb124b17     NA         0        0         2
5 5322 S1d75300     NA         0        0         0
6 5247 S1ef420d     NA         0        0         1
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2019-06-03 P060d440        0                   30          ⋯  0
2 2020-08-17 P14e664f        0                   32          ⋯  0
3 2021-01-28 P159f9c8        0                   38          ⋯  0
4 2021-01-06 P1a267fa        0                   34          ⋯  0
5 2019-05-14 P1d75300        0                   33          ⋯ NA
6 2020-09-17 P1ef420d        0                   30          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     38
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Unlaboured c-section NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Spontaneous          NA          NA    0

In [ ]:
# 5 write to file
write.table(kit_fp, file = paste0(Sys.Date(), "_kit_fp_", ".csv"), sep = ",", row.names = FALSE)
write.table(kit_sp, file = paste0(Sys.Date(), "_kit_sp_", ".csv"), sep = ",", row.names = FALSE)

In [ ]:
# Test file looks ok
#test_kit_fp <- read.csv("~/Programs/Programing_experiments/R/HT25_project/2025-07-29_kit_fp_.csv", header = TRUE)
#test_kit_sp <- read.csv("~/Programs/Programing_experiments/R/HT25_project/2025-07-29_kit_sp_.csv", header = TRUE)

In [ ]:
#glimpse(test_kit_fp)