#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: saliva_filtering_valid_barcodes_tp2
# Date: 2025.12.10
# Programmer: Barbara Nowak
# Purpose: Saliva, after Super StaG some samples failed, so matching of FP and SP valid samples had to be done again.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [6]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ─────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Read files --------------------------------------------------------------------------

In [10]:
# Taxa table where minimum abundance and prev species not removed
taxa_tab <- read.table("/ceph/projects/010_SweMaMi/bm.nowak/data/2025-12-09_no_minimum_prev_abundance_no_other_taxa_saliva_taxa_cleaned_both_tp.tsv", header = TRUE, sep ="\t", check.names = FALSE, quote='"') 
head(taxa_tab)
dim(taxa_tab)

                             11601   921     7766    11497   10644   7547
Prevotella_melaninogenica    7.46856 4.43305 2.01303 3.09323 2.18746  2.89516
TM7_phylum_sp_oral_taxon_352 3.14409 2.21632 0.27918 0.81149 0.10544  1.92240
Veillonella_dispar           3.16098 1.97065 5.15186 5.76151 3.67418  3.17602
Streptococcus_salivarius     6.66179 2.07087 9.56769 4.59215 7.84402 12.85163
Prevotella_pallens           1.09428 4.69337 0.48324 3.19061 0.00000  0.86855
Streptococcus_parasanguinis  5.05936 5.04811 4.55327 3.91857 2.32197  3.38418
                             10048   10681   13611   1054     ⋯ 19612   17589
Prevotella_melaninogenica    5.46348 7.60818 2.66597  7.05540 ⋯ 2.27635 3.91719
TM7_phylum_sp_oral_taxon_352 1.88095 0.70932 2.10826  1.12378 ⋯ 2.03540 1.91947
Veillonella_dispar           4.86584 7.54436 0.60527 13.37827 ⋯ 2.17340 6.97362
Streptococcus_salivarius     7.59421 8.05424 0.36229 23.52221 ⋯ 3.08711 3.59449
Prevotella_pallens           4.79881 1.50316 1.29621  0.03604 ⋯ 0.62355 1.68677
Streptococcus_parasanguinis  3.75756 4.71644 1.78240 11.06978 ⋯ 1.56545 3.28812
                             18881    21225   20293   21180   21386   21930
Prevotella_melaninogenica     0.01522 1.55264 4.93655 6.53807 3.30094 8.66169
TM7_phylum_sp_oral_taxon_352  0.99134 2.07174 0.46493 1.60654 3.36108 1.29958
Veillonella_dispar            9.72087 7.87567 7.26205 7.27621 5.88949 0.93840
Streptococcus_salivarius     18.06276 6.99764 9.51983 2.35358 6.62331 1.23692
Prevotella_pallens            0.52037 2.04457 2.32954 3.84069 0.71656 1.85049
Streptococcus_parasanguinis   9.99736 7.00401 2.73461 3.21385 7.10522 3.96688
                             17260    18891
Prevotella_melaninogenica     3.93085 3.41636
TM7_phylum_sp_oral_taxon_352  1.20771 1.13150
Veillonella_dispar           12.13797 1.20559
Streptococcus_salivarius     12.70253 6.49664
Prevotella_pallens            1.24524 0.92643
Streptococcus_parasanguinis   9.57804 1.01967

[1]  845 1673

In [2]:
fp_tp2 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp2_nulliparous/2025-12-10_fp_tp2_nulliparous.csv", header = TRUE)
dim(fp_tp2)
head(fp_tp2)

[1]   8 565

  Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 NA         0        0         0                     2018-03-07
2 NA         0        0         0                     2018-06-23
3 NA         0        0         0                     2018-07-09
4 NA         0        0         0                     2018-08-24
5 NA         0        0         2                     2018-08-21
6 NA         0        0         0                     2018-07-03
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups Swedish_born ⋯
1 P1f862a6        0                   32          3          1            ⋯
2 P3db7da6        0                   29          2          1            ⋯
3 P719b21e        0                   29          2          1            ⋯
4 P735d77f        0                   25          2          1            ⋯
5 P92b4604        0                   35          4          1            ⋯
6 Pbbb08bd        0                   33          3          1            ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     31
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          very_w28_31  1    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

In [3]:
sp_tp2 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp2_nulliparous//2025-12-10_sp_tp2_nulliparous.csv", header = TRUE)
dim(sp_tp2)
head(sp_tp2)

[1]   8 565

  Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 NA         0        0         1                     2019-01-17
2 NA         0        0         1                     2019-09-24
3 NA         0        0         0                     2020-06-01
4 NA         0        0         0                     2019-11-20
5 NA         0        0         2                     2020-04-06
6 NA         0        0         1                     2019-11-15
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups Swedish_born ⋯
1 P1f862a6        0                   32          3          1            ⋯
2 P3db7da6        0                   30          3          1            ⋯
3 P719b21e        0                   31          3          1            ⋯
4 P735d77f        0                   26          2          1            ⋯
5 P92b4604        0                   37          4          1            ⋯
6 Pbbb08bd        0                   34          3          1            ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Induction            NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Unlaboured c-section NA          NA    0
  Group
1 Second pregnancy
2 Second pregnancy
3 Second pregnancy
4 Second pregnancy
5 Second pregnancy
6 Second pregnancy

    combined_fp_sp_tp1 <- read.csv("/ceph/projects//010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/2025-10-22_combined_nulliparous_fp_sp_tp1_saliva.csv", header = TRUE)
dim(combined_fp_sp_tp1)
head(combined_fp_sp_tp1)

# Find valid barcodes ------------------------------------------------------------------------------

In [7]:
# Read fp and sp metadata files to obtain barcodes, OBS $Group for FP has a SPACE at the end!!
fp_bc <- fp_tp2 |>
  filter(Group == "First pregnancy ") |>
  pull(kit2.salival_sample.barcode)
print(fp_bc) |> length()

[1]  9226  1628 11722 13439 13165 10074  8127  7372

[1] 8

In [8]:
sp_bc <- sp_tp2 |>
  filter(Group == "Second pregnancy") |>
  pull(kit2.salival_sample.barcode)
print(sp_bc) |> length()

[1] 15399 17232 19335 18192 20183 21481 17263 19613

[1] 8

FP is the one that has less barcodes extract those since participants will be removed form SP if they are missing int FP.  
Then check what pn numbers correspont to those barcodes <-- this is what the filtering will then be based on.

In [11]:
valid_barcodes_fp <- taxa_tab[, colnames(taxa_tab) %in% fp_bc] |> colnames()

valid_barcodes_fp
length(valid_barcodes_fp)

[1] "10074" "1628"

[1] 2

In [14]:
invalid_pn_fp <- fp_tp2 |> filter(!fp_tp2$kit2.salival_sample.barcode %in% valid_barcodes_fp) |> pull(Q1_Personnummer)
length(invalid_pn_fp)
    head(invalid_pn_fp)

[1] 6

[1] "P1f862a6" "P719b21e" "P735d77f" "P92b4604" "Pcd2c0d1" "Pe706703"

In [15]:
valid_barcodes_sp <- taxa_tab[, colnames(taxa_tab) %in% sp_bc] |> colnames()

valid_barcodes_sp
length(valid_barcodes_sp)

[1] "19335" "17232" "15399" "21481" "18192" "17263" "19613"

[1] 7

In [16]:
invalid_pn_sp <- sp_tp2 |> filter(!sp_tp2$kit2.salival_sample.barcode %in% valid_barcodes_sp) |> pull(Q1_Personnummer)
length(invalid_pn_sp)
    head(invalid_pn_sp)

[1] 1

[1] "P92b4604"

In [17]:
class(valid_barcodes_fp)
class(valid_barcodes_sp)

[1] "character"

[1] "character"

In [18]:
intersect(invalid_pn_sp, invalid_pn_sp) |> length()
unique(invalid_pn_fp, invalid_pn_sp) |> length()

[1] 1

[1] 6

In [19]:
unique(invalid_pn_fp, invalid_pn_sp) |> length()

[1] 6

In [20]:
# combine both personal number to drop
pn_to_drop <- c(invalid_pn_fp, invalid_pn_sp)
pn_to_drop |> length()
pn_to_drop |> unique() |> length()

[1] 7

[1] 6

In [21]:
fp_tp2_saliva <- fp_tp2 |>
    filter(!(Q1_Personnummer %in% pn_to_drop))
head(fp_tp2_saliva)
dim(fp_tp2_saliva)

  Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 NA         0        0         0                     2018-06-23
2 NA         0        0         0                     2018-07-03
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups Swedish_born ⋯
1 P3db7da6        0                   29          2          1            ⋯
2 Pbbb08bd        0                   33          3          1            ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
  Group
1 First pregnancy
2 First pregnancy

[1]   2 565

In [22]:
sp_tp2_saliva <- sp_tp2 |>
    filter(!(Q1_Personnummer %in% pn_to_drop))
head(sp_tp2_saliva)
dim(sp_tp2_saliva)

  Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 NA         0        0         1                     2019-09-24
2 NA         0        0         1                     2019-11-15
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups Swedish_born ⋯
1 P3db7da6        0                   30          3          1            ⋯
2 Pbbb08bd        0                   34          3          1            ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     39
2 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Unlaboured c-section NA          NA    0
  Group
1 Second pregnancy
2 Second pregnancy

[1]   2 565

# Export data --------------------------------------------------------------------------

In [ ]:
# Export metadata tables
# Write to file
#write.table(fp_tp1_saliva, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/", 
 #                                         Sys.Date(), "_no_min_abundance_fp_tp1_nulliparous_saliva", ".csv"), sep = ",", 
  #          row.names = FALSE)

#write.table(sp_tp1_saliva, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/",
 #                                         Sys.Date(), "_no_min_abundance_sp_tp1_nulliparous_saliva", ".csv"), sep = ",", 
  #          row.names = FALSE)

In [23]:
# Combine both df
# Merge the two df vertically:
combined_fp_sp <- rbind(fp_tp2_saliva, sp_tp2_saliva)
dim(combined_fp_sp)
head(combined_fp_sp)

[1]   4 565

  Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 NA         0        0         0                     2018-06-23
2 NA         0        0         0                     2018-07-03
3 NA         0        0         1                     2019-09-24
4 NA         0        0         1                     2019-11-15
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups Swedish_born ⋯
1 P3db7da6        0                   29          2          1            ⋯
2 Pbbb08bd        0                   33          3          1            ⋯
3 P3db7da6        0                   30          3          1            ⋯
4 Pbbb08bd        0                   34          3          1            ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     40
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Unlaboured c-section NA          NA    0
  Group
1 First pregnancy
2 First pregnancy
3 Second pregnancy
4 Second pregnancy

In [57]:
#write.table(combined_fp_sp, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/", 
 #                                         Sys.Date(), "_no_min_abundance_combined_nulliparous_fp_sp_tp1_saliva", ".csv"), sep = ",", 
  #          row.names = FALSE)