#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: saliva_flowcells
# Date: 2025.10.16
# Programmer: Barbara Nowak
# Purpose: Find the flowcells IDs for valid kit1 samples (those only filtered for: is.na(kit1.salival_sample.barcode)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [62]:
library(tidyverse)
library(dplyr)

# Read files =================================================================================================

In [63]:
combined_metadata <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/2025-10-16combined_for_flowcells_saliva.csv", header = TRUE, row.names = 1)
head(combined_metadata)
dim(combined_metadata)

         Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
Scf5931f NA         0        0         0                     2018-12-13
S14e664f NA         0        0         1                     2018-09-10
S30bce16 NA         0        0         0                     2018-04-18
S1f862a6 NA         0        0         0                     2018-03-07
S765e59d NA         0        0         1                     2018-04-20
S3780ac4 NA         0        0         0                     2019-02-23
         Q1_Personnummer Avbruten_graviditet age_checked Age_groups
Scf5931f P060d440        0                   30          3
S14e664f P14e664f        0                   30          3
S30bce16 P1d75300        0                   32          3
S1f862a6 P1f862a6        0                   32          3
S765e59d P3399626        0                   36          4
S3780ac4 P3780ac4        0                   38          4
         Swedish_born ⋯ diffdays missfall.IUFD_week IUFD missfall
Scf5931f 1            ⋯ NA       NA                 NA    1
S14e664f 1            ⋯  0       NA                 NA   NA
S30bce16 1            ⋯ NA       NA                 NA   NA
S1f862a6 1            ⋯  0       NA                 NA   NA
S765e59d 1            ⋯  0       NA                 NA   NA
S3780ac4 1            ⋯ NA       NA                 NA   NA
         missfall.IUFD_comments Gest_w_combined deliv_start_combined
Scf5931f MISSED ABORTION        NA              NA
S14e664f NA                     39              Induction
S30bce16 NA                     NA              NA
S1f862a6 NA                     31              Spontaneous
S765e59d NA                     39              Spontaneous
S3780ac4 NA                     NA              NA
         Type_of_PTB s_PTB preeclampsia_epi_analysis
Scf5931f NA          NA    0
S14e664f NA          NA    0
S30bce16 NA          NA    0
S1f862a6 very_w28_31  1    0
S765e59d NA          NA    0
S3780ac4 NA          NA    0

[1]  64 564

In [64]:
saliva_samples <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/data/saliva_samples_250923.csv", header = TRUE, row.names = 1)
head(saliva_samples)
dim(saliva_samples)

  project_id  sequencer_id   flowcell_id lane_id adaptor_id sample_id
1 010_SweMaMi R1100600190018 E200005523  1       114        10009
2 010_SweMaMi R1100600190018 E100073553  1        99        10020
3 010_SweMaMi R1100600190018 E100073527  1        64        10021
4 010_SweMaMi R1100600190018 E111174961  1        64        10021
5 010_SweMaMi R1100600190018 E100073553  1        85        10026
6 010_SweMaMi R1100600190018 E100073553  1       102        10028
  extraction_id            V8      V9     V10         V11 V12      V13
1 010_saliva_extraction23  41.8620 34.805 0.000784011 466 59201249 66.68
2 010_saliva_extraction2   29.0870 30.304          NA 457       NA    NA
3 010_saliva_extraction_12  3.3432 44.298          NA 455       NA    NA
4 010_saliva_extraction_12  3.3432 44.298          NA 455       NA    NA
5 010_saliva_extraction2   39.4890 34.092          NA 457       NA    NA
6 010_saliva_extraction2   60.4390 40.887          NA 457       NA    NA
  V14      V15
1 19725508
2       NA
3       NA
4       NA
5       NA
6       NA

[1] 2863   15

# TP1----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [65]:
grep("kit1", names(combined_metadata), value = TRUE)

[1] "kit1.faecal_sample.barcode"         "kit1.salival_sample.barcode"
[3] "kit1.vaginal_sample.barcode"        "kit1.faecal_sample.datetime_taken"
[5] "kit1.salival_sample.datetime_taken" "kit1.vaginal_sample.datetime_taken"

In [66]:
head(combined_metadata$kit1.salival_sample.barcode)

[1]  1810 11667  7562  1220  7197 13129

In [67]:
# Find sample ids that are valid
sample_ids_to_pull <- combined_metadata |>
    pull(kit1.salival_sample.barcode)
length(sample_ids_to_pull)
head(sample_ids_to_pull)

[1] 64

[1]  1810 11667  7562  1220  7197 13129

In [68]:
# Pull only valid sample ids
flowcell_ids <- saliva_samples |>
    filter(sample_id %in% sample_ids_to_pull) |>
    pull(flowcell_id)
length(flowcell_ids)

[1] 52

In [69]:
head(flowcell_ids)

[1] "E200013398" "E100073476" "E100074733" "E100073553" "E100073553"
[6] "E200013398"

In [70]:
class(flowcell_ids)

[1] "character"

# TP2----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [71]:
# Find sample ids that are valid for kit2 in 
sample_ids_to_pull_kit2 <- combined_metadata |>
    filter(!(is.na(kit2.salival_sample.barcode))) |>
    pull(kit2.salival_sample.barcode)
length(sample_ids_to_pull_kit2)
head(sample_ids_to_pull_kit2)

[1] 40

[1] 12735  9226 10501  1628  8011 12709

In [72]:
# Pull only valid sample ids
flowcell_ids_kit2 <- saliva_samples |>
    filter(sample_id %in% sample_ids_to_pull_kit2) |>
    pull(flowcell_id)
length(flowcell_ids_kit2)

[1] 43

# Write to file ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Save valid flow cell ids to .txt file

In [73]:
writeLines(flowcell_ids, file.path("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/flowcells/", paste0(Sys.Date(), "_flowcell_ids_kit1.txt")))

In [79]:
writeLines(flowcell_ids_kit2, file.path("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/flowcells/", paste0(Sys.Date(), "_flowcell_ids_kit2.txt")))

In [84]:
all_flow_cell_id <- c(flowcell_ids , flowcell_ids_kit2)
flowcell_id_uni <- unique(all_flow_cell_id )

In [85]:
# Write a combined file
writeLines(flowcell_id_uni, file.path("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/flowcells/", paste0(Sys.Date(), "flowcell_id_uni.txt")))